management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

server:
  port: 8080

---
spring:
  config:
    active:
      on-profile: server
  data:  
    rest:
      base-path: /api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

---
spring:
  config:
    active:
      on-profile: client
  # autoconfigure:
  #   exclude: 
  #   - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  #   - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

