management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

spring:
  # config:
  #   import: "kubernetes:"
  data:  
    rest:
      base-path: /api
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  
    hibernate:
      auto-ddl: update
