apiVersion: v1
kind: Service
metadata:
  name: rest-app-service
  namespace: postgres-performance
spec:
  selector:
    app: rest-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP